name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: app-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            app-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            app-${{ env.cache-name }}-
            app-

      - name: Cache .next
        uses: actions/cache@v3
        env:
          cache-name: cache-next
        with:
          path: .next
          key: app-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            app-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            app-${{ env.cache-name }}-
            app-

      - run: yarn install
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run format
